#!/bin/sh

# build gist library
cd 3rdparty/lear_gist-1.2/
./build.sh
cd ../..
cp 3rdparty/lear_gist-1.2/src/gist.h include/
cp 3rdparty/lear_gist-1.2/src/fftw3.h include/
cp 3rdparty/lear_gist-1.2/src/*.a lib/

rm -f 3rdparty/lear_gist-1.2/src/fftw3.h
rm -f 3rdparty/lear_gist-1.2/src/*.a

# build vlfeat library
cd 3rdparty/vlfeat
make
cp -r vl ../../include/
if [ -e bin/glnxa64/libvl.so ]
then
    cp bin/glnxa64/libvl.so ../../lib/
else
    cp bin/glnx86/libvl.so ../../lib/
fi

make clean

cd ../..

echo "export LD_LIBRARY_PATH=lib/:$LD_LIBRARY_PATH" >> $HOME/.bashrc
source $HOME/.bashrc

scons
