#!/bin/sh

# build git library
cd 3rdparty/lear_gist-1.2/
./build.sh
cd ../..
cp 3rdparty/lear_gist-1.2/src/gist.h include/
cp 3rdparty/lear_gist-1.2/src/fftw3.h include/
cp 3rdparty/lear_gist-1.2/src/lib*.a lib/

# build vlfeat library
cd 3rdparty/vlfeat
make
cp -r vl ../../include/
if [ -e bin/glnxa64/libvl.so ]
then
    cp bin/glnxa64/libvl.so ../../lib/
else
    cp bin/glnx86/libvl.so ../../lib/
fi

make clean

cd ../..

scons
